stages:
    - build
    - containerize

build_jar:
  image: maven:3.8-openjdk-17
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/stock-ms.jar

build_image:
  image: docker
  stage: containerize
  services:
    - docker:dind
  needs:
    - build_jar
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/mainprogram1/microservice_ms/microservice_ms:latest .
    - docker push $CI_REGISTRY/mainprogram1/microservice_ms/microservice_ms:latest
    - echo "Image built !"